### ISSUE TITLE
What is this system?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/acore-php-framework#1]
The complete World of Warcraft private server site?
OR
Just PHP Framework?

**Comment by Yehonal** [comment]
2017 :-/

BTW, it's a framework that's used for our [CMS ](https://github.com/azerothcore/acore-cms) at the moment, but anyone can integrate it into its own system to query/mutate the database or doing soap calls

**Comment by FrancescoBorzi** [comment]
> 2017 :-/

better late than never :D
